// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Kafka.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("KafkaBrokers")]
    public partial class KafkaBrokersFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "KafkaBrokers.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "KafkaBrokers", "In order to avoid silly mistakes\r\nAs an Kafka amateur\r\nI want to consume Kafka me" +
                    "tadata", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Able to resolve kafka broker names to ip in host file")]
        [NUnit.Framework.CategoryAttribute("FileProc_Kafka_produce")]
        public virtual void AbleToResolveKafkaBrokerNamesToIpInHostFile()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Able to resolve kafka broker names to ip in host file", new string[] {
                        "FileProc_Kafka_produce"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 19
  testRunner.Given("I have brokers for kafka from AcceptanceTest:KafkaUri", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
  testRunner.When("I read host file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "ip machine"});
            table1.AddRow(new string[] {
                        "172.26.15.7 rhi-fuse-dev-cluster-kafka0.westus.cloudapp.azure.com rhi-fuse-dev-cl" +
                            "uster-mn0.westus.cloudapp.azure.com"});
            table1.AddRow(new string[] {
                        "172.26.15.5 rhi-fuse-dev-cluster-kafka1.westus.cloudapp.azure.com rhi-fuse-dev-cl" +
                            "uster-mn1.westus.cloudapp.azure.com"});
            table1.AddRow(new string[] {
                        "172.26.15.9 rhi-fuse-dev-cluster-kafka2.westus.cloudapp.azure.com rhi-fuse-dev-cl" +
                            "uster-mn2.westus.cloudapp.azure.com"});
#line 21
  testRunner.Then("It should contain", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Able to produce and consume kafka to topic - junk")]
        [NUnit.Framework.CategoryAttribute("FileProc_Kafka_produce")]
        public virtual void AbleToProduceAndConsumeKafkaToTopic_Junk()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Able to produce and consume kafka to topic - junk", new string[] {
                        "FileProc_Kafka_produce"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 30
  testRunner.Given("I have brokers for kafka from AcceptanceTest:KafkaUri", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 31
    testRunner.And("I have Random expressions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
  testRunner.When("I send it to kafka junk topic", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
  testRunner.Then("I should consume it in 0 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Able to consume kafka - fusedev")]
        [NUnit.Framework.CategoryAttribute("FileProc_Kafka_consume")]
        public virtual void AbleToConsumeKafka_Fusedev()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Able to consume kafka - fusedev", new string[] {
                        "FileProc_Kafka_consume"});
#line 36
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 37
  testRunner.Given("I have brokers for kafka from AcceptanceTest:KafkaUri", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "topic",
                        "info"});
            table2.AddRow(new string[] {
                        "fusetest",
                        "--"});
            table2.AddRow(new string[] {
                        "junk",
                        "4 messages"});
            table2.AddRow(new string[] {
                        "Practitioner",
                        "10 messages"});
            table2.AddRow(new string[] {
                        "Patient",
                        "4 messages"});
            table2.AddRow(new string[] {
                        "Procedure",
                        "4 messages"});
            table2.AddRow(new string[] {
                        "Organization",
                        "4 messages  v1"});
            table2.AddRow(new string[] {
                        "Claim",
                        "4 messages  v1"});
            table2.AddRow(new string[] {
                        "Coverage",
                        "2 messages  v1"});
            table2.AddRow(new string[] {
                        "Location",
                        "2 messages  v1"});
            table2.AddRow(new string[] {
                        "Logpoc",
                        "2 messages  v1"});
            table2.AddRow(new string[] {
                        "Condition",
                        "FirstOffset: 258; Items: 7"});
            table2.AddRow(new string[] {
                        "DiagnosticReport",
                        "FirstOffset: 61; Items: 2 (53, 10)"});
            table2.AddRow(new string[] {
                        "Encounter",
                        "2 messages  v1"});
            table2.AddRow(new string[] {
                        "FamilyMemberHistory",
                        "FirstOffset: 16; Items: 2"});
            table2.AddRow(new string[] {
                        "Immunization",
                        "FirstOffset: 129; Items: 3"});
            table2.AddRow(new string[] {
                        "Medication",
                        "FirstOffset: 396; Items: 4"});
            table2.AddRow(new string[] {
                        "AllergyIntolerance",
                        "FirstOffset: 51; Items: 8"});
            table2.AddRow(new string[] {
                        "mt-event-mex",
                        ""});
            table2.AddRow(new string[] {
                        "mt-event-test",
                        ""});
            table2.AddRow(new string[] {
                        "mt-reindex",
                        ""});
#line 38
  testRunner.And("I have topics for kafka", ((string)(null)), table2, "And ");
#line 61
  testRunner.When("I call kafka server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
  testRunner.Then("I should retrieve last 2 messages in -1 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Able to get data folder")]
        [NUnit.Framework.CategoryAttribute("FileProc_Kafka_datafolder")]
        public virtual void AbleToGetDataFolder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Able to get data folder", new string[] {
                        "FileProc_Kafka_datafolder"});
#line 66
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "kafka broker"});
            table3.AddRow(new string[] {
                        "172.26.15.7:19092"});
#line 67
  testRunner.Given("I have brokers for kafka", ((string)(null)), table3, "Given ");
#line 71
  testRunner.When("I call kafka server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 72
  testRunner.Then("data folder is created if missing", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Able to consume kafka listed topics from app.config")]
        [NUnit.Framework.CategoryAttribute("FileProc_Kafka_consume")]
        public virtual void AbleToConsumeKafkaListedTopicsFromApp_Config()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Able to consume kafka listed topics from app.config", new string[] {
                        "FileProc_Kafka_consume"});
#line 75
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 76
  testRunner.Given("I have brokers for kafka from AcceptanceTest:KafkaUri", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 77
   testRunner.And("I have topic list for kafka dummy, test1, junk, fusetest, Claim,", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
   testRunner.And("I have topic list for kafka Coverage, Immunization, Location,Logpoc", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
   testRunner.And("I have topic list for kafka Medication, Organization, Patient, Procedure, Practit" +
                    "ioner", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
  testRunner.When("I call kafka server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 81
  testRunner.Then("I should retrieve last 2 messages in -1 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Able to consume kafka config topics from app.config")]
        [NUnit.Framework.CategoryAttribute("FileProc_Kafka_consume")]
        public virtual void AbleToConsumeKafkaConfigTopicsFromApp_Config()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Able to consume kafka config topics from app.config", new string[] {
                        "FileProc_Kafka_consume"});
#line 84
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 85
  testRunner.Given("I have brokers for kafka from AcceptanceTest:KafkaUri", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 86
    testRunner.And("I have topic list AcceptanceTest:KafkaTopicsAll for kafka", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
   testRunner.Then("I should retrieve last 2 messages in -1 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Able to consume kafka topic from app.config")]
        [NUnit.Framework.CategoryAttribute("FileProc_Kafka_consume")]
        [NUnit.Framework.TestCaseAttribute("fusetest", null)]
        [NUnit.Framework.TestCaseAttribute("junk", null)]
        [NUnit.Framework.TestCaseAttribute("Practitioner", null)]
        [NUnit.Framework.TestCaseAttribute("Location", null)]
        [NUnit.Framework.TestCaseAttribute("Patient", null)]
        [NUnit.Framework.TestCaseAttribute("Procedure", null)]
        [NUnit.Framework.TestCaseAttribute("Organization", null)]
        [NUnit.Framework.TestCaseAttribute("Claim", null)]
        [NUnit.Framework.TestCaseAttribute("Coverage", null)]
        public virtual void AbleToConsumeKafkaTopicFromApp_Config(string topic, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "FileProc_Kafka_consume"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Able to consume kafka topic from app.config", @__tags);
#line 90
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 91
  testRunner.Given("I have brokers for kafka from AcceptanceTest:KafkaUri", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 92
  testRunner.And(string.Format("I have kafka {0}", topic), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 93
  testRunner.When("I call kafka server", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 94
  testRunner.Then("I should retrieve last 2 messages in -1 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Able to parse json message Patient")]
        [NUnit.Framework.CategoryAttribute("FileProc_Json")]
        public virtual void AbleToParseJsonMessagePatient()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Able to parse json message Patient", new string[] {
                        "FileProc_Json"});
#line 109
  this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 110
  testRunner.Given("I have json file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 111
  testRunner.When("I parse it", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "jsonpath",
                        "value"});
            table4.AddRow(new string[] {
                        "name[0].family[0]",
                        "LAMBERT"});
            table4.AddRow(new string[] {
                        "address[0].addressLine[0]",
                        "7881 Metus Street"});
            table4.AddRow(new string[] {
                        "address[0].addressLine[1]",
                        "none"});
            table4.AddRow(new string[] {
                        "address[0].addressLine[2]",
                        "null"});
#line 112
  testRunner.Then("I should be find in file <messages\\Patient\\item_215.json> matching json values", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Able to parse json message Condition")]
        [NUnit.Framework.CategoryAttribute("FileProc_Json")]
        public virtual void AbleToParseJsonMessageCondition()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Able to parse json message Condition", new string[] {
                        "FileProc_Json"});
#line 120
  this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 121
  testRunner.Given("I have json file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 122
  testRunner.When("I parse it", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "jsonpath",
                        "value"});
            table5.AddRow(new string[] {
                        "category.coding[?(@.code==\'ccc\')].system",
                        "xxx"});
            table5.AddRow(new string[] {
                        "code.coding[0].code",
                        "V04.81"});
            table5.AddRow(new string[] {
                        "category.coding[0].code",
                        "55607006"});
            table5.AddRow(new string[] {
                        "category.coding[0].primary",
                        "True"});
            table5.AddRow(new string[] {
                        "onset.onsetDateTime.offset",
                        "0"});
#line 123
  testRunner.Then("I should be find in file <messages\\Condition\\item_257.json> matching json values", ((string)(null)), table5, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Able to parse xml message with XmlResolver")]
        [NUnit.Framework.CategoryAttribute("Xml_validation_XXE")]
        public virtual void AbleToParseXmlMessageWithXmlResolver()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Able to parse xml message with XmlResolver", new string[] {
                        "Xml_validation_XXE"});
#line 132
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 133
testRunner.Given("I have xml content", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 134
testRunner.When("I load it", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 135
testRunner.Then("It should be loaded as xmldoc.Load(xmlreader) loaded with DtdProcessing.Prohibit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 136
 testRunner.And("It should be loaded as xmldoc.Load(string) with CustomUrlResovler", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 137
 testRunner.And("It should be loaded as xdocument.Load(xmlreader) with DtdProcessing.Prohibit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 138
 testRunner.And("It should be deserialized as xmlSerializer.Deserialize(xmlreader) with DtdProcess" +
                    "ing.Prohibit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 139
 testRunner.And("xml file should be cleaned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
